### ISSUE TITLE
Label the Consoles

### ISSUE THREAD

**Issue by ALRubinger** [fabric8-launcher/launcher-creator-welcome-app#36]
Will submit PR for @ia3andy review

**Comment by ALRubinger** [comment]
Sending to @ia3andy to review/accept 9b949ed in #37

**Comment by ia3andy** [comment]
Closed by https://github.com/fabric8-launcher/launcher-creator-welcome-app/commit/4a9f0e549e2a78c3aa9f4d4ced230f2312726588
