### ISSUE TITLE
Convert src/data/ApplicationProfile.tsx to use a pure JSON object

### ISSUE THREAD

**Issue by ALRubinger** [fabric8-launcher/launcher-creator-welcome-app#4]
Should preserve the type checking done when brought in by the system in https://github.com/fabric8-launcher/launcher-creator-welcome-app/blob/master/src/app/App.tsx#L14 (refers to the actual config that you can find here: https://github.com/fabric8-launcher/launcher-creator-welcome-app/blob/master/src/app/landing/data/ApplicationProfile.tsx)

**Comment by ia3andy** [comment]
Here you can find the definition of the json config file that will be added to the public directory of the welcome-app:
https://hackmd.io/9tTtUndKSA6XA-RZcCd9ww
