### ISSUE TITLE
In "Cloud Deployment" section, add link to "Frontend (React) Application" if it had been selected

### ISSUE THREAD

**Issue by ALRubinger** [fabric8-launcher/launcher-creator-welcome-app#59]

**Comment by quintesse** [comment]
Yes, although there's one trick we can use: we _know_ that the route that will be generated for the welcome app is of the form `launcher-welcome-app-APP_NAME.rest.of.the.host.name`. What we can do is take that URL, strip of the `launcher-welcome-app` and prepend the name of the service we're trying to reach. It's a bit of a hack perhaps, but it should work-

**Comment by ia3andy** [comment]
@quintesse sounds great to me
