### ISSUE TITLE
PUT message should handle unique fruit names errors

### ISSUE THREAD

**Issue by ghost** [fabric8-launcher/launcher-creator-welcome-app#61]
- Deploy a Thorntail app with the MySQL Database and REST capabilities enabled 
- Open the Welcome app and navigate to the Relational Database section
- Click on the **PUT** button without changing any parameters.
- Nothing happens

In the logs there is an error, but nothing is displayed in the welcome app console: 
```
Caused by: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'Banana' for key 'UK_57g3m8wr3qxoj706a6hsqg6ye'
 ```

**Comment by ALRubinger** [comment]
I wonder if this is best enforced by all the runtimes in the serverside layer.  Welcome app is a dumb client which sends requests to endpoints.

**Comment by gastaldi** [comment]
Probably the title is misleading. I mean that the client doesn't seem to handle error messages coming from the server

**Comment by ia3andy** [comment]
Duplicate #39
