### ISSUE TITLE
Add link to Health Checks for the service in OpenShift Console in the card

### ISSUE THREAD

**Issue by ALRubinger** [fabric8-launcher/launcher-creator-welcome-app#65]

**Comment by ALRubinger** [comment]
Removing as MVP requirement

**Comment by ALRubinger** [comment]
Putting back in as MVP requirement; it's just a link.  The catch is that the Health Checks must actually be made in OpenShift, and presently, they're not.  That's tracked in https://github.com/fabric8-launcher/launcher-creator-backend/issues/72

**Comment by ia3andy** [comment]
@ALRubinger is this really necessary?

The url could easily be broken in future openshift releases:
https://console_url/project/APP_NAME/browse/dc/SERVICE_NAME?tab=configuration

**Comment by ALRubinger** [comment]
No, this is not necessary, as discussed in the call.  Closing.  Good point.
