### ISSUE TITLE
Get ready for demo

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/launcher-creator-welcome-app#72]
- Link to console must point to project overview
- Frontend first 
- `monospace` font for images
- source mapping use last part of source link

**Comment by ia3andy** [comment]
- use backend url for api calls

**Comment by ALRubinger** [comment]
"java" > "Java" in Backend codebase card
"javascript" > "JavaScript" in Frontend/Backend codebase cards

**Comment by ia3andy** [comment]
created #77 #78
