### ISSUE TITLE
Add a debug script in package.json to ease debugging

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-creator-welcome-app#74]
Just like https://github.com/fabric8-launcher/launcher-creator-backend/commit/ecca197a2bbc5537b7471b7b84f78f16202538cd#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 it would be nice to have a `npm debug` command to allow someone to debug the app

**Comment by ia3andy** [comment]
@gastaldi you can actually debug in the chrome developer console. Re-open if you feel this is not enough..
